#!/usr/bin/env python3
"""Official publisher rooms from comic.kagurabachi.jp/en/comics/."""
from ultra_lib import page

page(
    "collectibles/licenses.html",
    "Kagurabachi Licenses | Official Publishers by Language",
    "The official comics page lists Shueisha plus sixteen territorial publishers. This desk files each name. It does not list scans.",
    "Collect · 版権",
    "Official licenses",
    "各国版権",
    "Same book. Different cloth. The official table is the source.",
    [
        (
            "What the official page prints",
            [
                "comic.kagurabachi.jp/en/comics/ prints a language table: Japanese (Shueisha), Italian (Star Comics), Indonesian (PT Elex Media Komputindo), English (VIZ Media LLC), Korean (Daewon C.I.), Spanish Argentina (Ivrea), Spanish Spain (Planeta), Spanish Mexico (Panini), Thai (SMM PLUS), Simplified Chinese (Xiling Yinshe), Traditional Chinese Taiwan (Tong Li), Traditional Chinese Hong Kong and Macau (Jade Dynasty), Czech (CREW), German (Carlsen), French (Éditions Kana), Portuguese Portugal (DEVIR), Portuguese Brazil (Panini).",
                "This hub is the map. Each publisher has a room. VIZ’s English trades already have their own English-volume doors. Anime licenses (Crunchyroll, Muse) are not book licenses. We do not list scans. Buy the territorial object.",
            ],
        )
    ],
    [
        ("star-comics.html", "Star Comics"),
        ("kana.html", "Kana"),
        ("carlsen.html", "Carlsen"),
        ("english-volume-10.html", "English 10"),
        ("../media/editions.html", "Editions essay"),
        ("index.html", "Collectibles"),
    ],
)

LICENSES = [
    (
        "collectibles/star-comics.html",
        "Kagurabachi Italian Edition | Star Comics",
        "Star Comics holds the Italian book license on the official comics page.",
        "Collect · IT",
        "Star Comics",
        "イタリア語",
        "Italian cloth. Not a VIZ trade.",
        "Italian",
        "Star Comics",
        "The Italian edition is the Star Comics object. It is not the VIZ trade and not a scan. Buy it from the Italian shop if that is your language.",
    ),
    (
        "collectibles/elex.html",
        "Kagurabachi Indonesian Edition | Elex Media",
        "PT Elex Media Komputindo holds the Indonesian book license on the official comics page.",
        "Collect · ID",
        "Elex Media",
        "インドネシア語",
        "Indonesian cloth. Jump’s usual Jakarta door.",
        "Indonesian",
        "PT Elex Media Komputindo",
        "Elex is how a lot of Jump books reach Indonesian shelves. This desk files the name from the official table. It does not invent an ISBN.",
    ),
    (
        "collectibles/daewon.html",
        "Kagurabachi Korean Edition | Daewon C.I.",
        "Daewon C.I. holds the Korean book license on the official comics page.",
        "Collect · KR",
        "Daewon C.I.",
        "韓国語",
        "Korean cloth. A different hangul object.",
        "Korean",
        "Daewon C.I.",
        "Daewon is the Korean publisher the official page names. Crunchyroll’s anime exception list names South Korea separately. The book and the broadcast are different licenses.",
    ),
    (
        "collectibles/ivrea.html",
        "Kagurabachi Argentine Edition | Ivrea",
        "Ivrea holds the Spanish (Argentina) book license on the official comics page.",
        "Collect · AR",
        "Ivrea",
        "アルゼンチン",
        "Argentine Spanish. Not Planeta. Not Panini Mexico.",
        "Spanish (Argentina)",
        "Ivrea",
        "Three Spanish licenses sit on the official table. Ivrea is the Argentine one. Do not treat “Spanish Kagurabachi” as a single object.",
    ),
    (
        "collectibles/planeta.html",
        "Kagurabachi Spanish Edition | Planeta",
        "Planeta holds the Spanish (Spain) book license on the official comics page.",
        "Collect · ES",
        "Planeta",
        "スペイン",
        "Spain’s Spanish cloth. Not Ivrea. Not Panini Mexico.",
        "Spanish (Spain)",
        "Planeta",
        "Planeta is the Spain row. The other Spanish rows are Ivrea and Panini Mexico. Three publishers. Three shops.",
    ),
    (
        "collectibles/panini-mexico.html",
        "Kagurabachi Mexican Edition | Panini",
        "Panini holds the Spanish (Mexico) book license on the official comics page.",
        "Collect · MX",
        "Panini Mexico",
        "メキシコ",
        "Mexican Spanish. Panini also holds Brazil. Different language rows.",
        "Spanish (Mexico)",
        "Panini",
        "Panini appears twice on the official table: Mexico (Spanish) and Brazil (Portuguese). This room is the Mexican Spanish object.",
    ),
    (
        "collectibles/smm-plus.html",
        "Kagurabachi Thai Edition | SMM Plus",
        "SMM PLUS COMPANY LIMITED holds the Thai book license on the official comics page.",
        "Collect · TH",
        "SMM Plus",
        "タイ語",
        "Thai cloth. Muse holds the anime in the region. Different license.",
        "Thai",
        "SMM PLUS COMPANY LIMITED",
        "The Thai book is SMM Plus. Muse Communication is the South and Southeast Asia anime door. Do not collapse the two.",
    ),
    (
        "collectibles/xiling.html",
        "Kagurabachi Simplified Chinese Edition | Xiling Yinshe",
        "Xiling Yinshe Publishing House holds the Simplified Chinese book license on the official comics page.",
        "Collect · CN",
        "Xiling Yinshe",
        "簡体字",
        "Simplified Chinese cloth. Not Tong Li. Not Jade Dynasty.",
        "Simplified Chinese",
        "Xiling Yinshe Publishing House",
        "The official table splits Chinese three ways. This is the Simplified row. Crunchyroll’s anime announcement excepts mainland China. The book license is still a book license.",
    ),
    (
        "collectibles/tong-li.html",
        "Kagurabachi Taiwan Edition | Tong Li",
        "Tong Li Publishing holds the Traditional Chinese (Taiwan) book license on the official comics page.",
        "Collect · TW",
        "Tong Li",
        "台湾",
        "Taiwan Traditional Chinese. Not Hong Kong. Not Simplified.",
        "Traditional Chinese (Taiwan)",
        "Tong Li Publishing",
        "Tong Li is Jump’s usual Taiwan door. Jade Dynasty is the Hong Kong and Macau row. Two Traditional licenses. Two shops.",
    ),
    (
        "collectibles/jade-dynasty.html",
        "Kagurabachi Hong Kong Edition | Jade Dynasty",
        "Jade Dynasty Publications holds the Traditional Chinese (Hong Kong and Macau) book license on the official comics page.",
        "Collect · HK",
        "Jade Dynasty",
        "香港・澳門",
        "Hong Kong and Macau Traditional Chinese. Not Tong Li.",
        "Traditional Chinese (Hong Kong and Macau)",
        "Jade Dynasty Publications",
        "Jade Dynasty is the Hong Kong and Macau row. Tong Li is Taiwan. Xiling is Simplified. The official table refuses to merge them.",
    ),
    (
        "collectibles/crew.html",
        "Kagurabachi Czech Edition | CREW",
        "CREW holds the Czech book license on the official comics page.",
        "Collect · CZ",
        "CREW",
        "チェコ語",
        "Czech cloth. A Central European Jump door.",
        "Czech",
        "CREW",
        "CREW is the Czech publisher the official page names. This desk files the language row. It does not invent a first-volume date.",
    ),
    (
        "collectibles/carlsen.html",
        "Kagurabachi German Edition | Carlsen",
        "Carlsen Verlag GmbH holds the German book license on the official comics page.",
        "Collect · DE",
        "Carlsen",
        "ドイツ語",
        "German cloth. Carlsen’s Jump shelf.",
        "German",
        "Carlsen Verlag GmbH",
        "Carlsen is the German row. AnimagiC hosted a world-tour twenty minutes in 2026. The book and the screening are different objects.",
    ),
    (
        "collectibles/kana.html",
        "Kagurabachi French Edition | Éditions Kana",
        "Éditions Kana holds the French book license on the official comics page. Volume 11 promo already named it.",
        "Collect · FR",
        "Éditions Kana",
        "フランス語",
        "French cloth. Japan Expo saw the twenty-minute tour.",
        "French",
        "Éditions Kana",
        "Kana was already on this archive from Volume 11 promo. The official comics page now lists Éditions Kana as the French publisher. Japan Expo 2026 also hosted the first-twenty-minutes tour and the Daruma for Best Action Manga.",
    ),
    (
        "collectibles/devir.html",
        "Kagurabachi Portuguese Edition | DEVIR",
        "DEVIR holds the Portuguese (Portugal) book license on the official comics page.",
        "Collect · PT",
        "DEVIR",
        "ポルトガル",
        "Portugal’s Portuguese cloth. Not Panini Brazil.",
        "Portuguese (Portugal)",
        "DEVIR",
        "Two Portuguese licenses sit on the official table. DEVIR is Portugal. Panini is Brazil. Do not buy the wrong alphabet’s neighbor and call it the same book.",
    ),
    (
        "collectibles/panini-brazil.html",
        "Kagurabachi Brazilian Edition | Panini",
        "Panini holds the Portuguese (Brazil) book license on the official comics page.",
        "Collect · BR",
        "Panini Brazil",
        "ブラジル",
        "Brazilian Portuguese. Panini also holds Mexico. Different language rows.",
        "Portuguese (Brazil)",
        "Panini",
        "This is the Brazil row. Mexico is the other Panini row, in Spanish. Two countries. Two languages. One company name on the table.",
    ),
]

for rel, title, desc, kicker, h1, jp, lede, lang, pub, extra in LICENSES:
    page(
        rel,
        title,
        desc,
        kicker,
        h1,
        jp,
        lede,
        [
            (
                "The official row",
                [
                    f"The official Kagurabachi comics page lists <strong>{lang}</strong> under <strong>{pub}</strong>. That is the license this room files. Shueisha remains the Japanese Jump Comics publisher. VIZ remains the English simulpub and trade publisher.",
                    extra + " Hub: <a href=\"licenses.html\">all licenses</a>. English trades: <a href=\"english-volume-9.html\">volume 9</a> and <a href=\"english-volume-10.html\">volume 10</a>. Shop stays off the homepage.",
                ],
            )
        ],
        [
            ("licenses.html", "All licenses"),
            ("../media/editions.html", "Editions"),
            ("jump-comics.html", "Jump Comics"),
            ("../manga/publication.html", "Publication"),
            ("shop.html", "Shop"),
            ("index.html", "Collectibles"),
        ],
    )

print("ultra_licenses done")
